image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
- npm ci

pages:
  script:
  - mv src public
  artifacts:
    paths:
    - public
  only:
  - master
