image: oven/bun:latest
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
  - node_modules/
before_script:
- bun install --frozen-lockfile
test:
  script:
  - bun run lint
  - bun run test
pages:
  script:
  - bun run build
  artifacts:
    paths:
    - public
  only:
  - main
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml

