image: oven/bun:latest
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
  - node_modules/
stages:
- test
test:
  script:
  - bun install --frozen-lockfile
  - bun run lint
  - bun run test
pages:
  script:
  - bun install --frozen-lockfile
  - bun run build
  artifacts:
    paths:
    - public
  only:
  - main
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
sast:
  stage: test
